# image: node:latest

# variables:
#   GIT_DEPTH: 1000000

# stages:
#   - deploy

# deploy to production:
#   stage: deploy
#   environment:
#     name: production
#   only:
#     - master
#   script: ./git-push-prod.sh dokku@vps-ac0d236a.vps.ovh.net:api


# deploy to development:
#   stage: deploy
#   environment:
#     name: development
#   only:
#     - develop
#   script: ./git-push-prod.sh dokku@vps-ac0d236a.vps.ovh.net:dev-api

stages:
  - build
 

docker-build:
  
  image: docker:latest
  stage: build
  only:
    - develop
  services:
    - docker:dind
  tags:
    - inaya-dock
  before_script:
    - docker login -u ELBouslama -p "$AcessKey" $CI_REGISTRY
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"
  # Run this job in a branch where a Dockerfile exists
  
